Module2 task1
htmlacademy-adaptive/323345-cat-energy-1 pull request #2
Opened 2024-01-18 11:42 UTC by licos87

2024-01-20 16:34 UTC, vadimrahmanov requested changes

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <ul class="header__nav main-menu">
одинаковые классы здесь и у элемента nav

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <button class="main-menu-toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
тут main-menu__toggle

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <img class="promo__cat-img" src="./img/booklet-img-cat-small.png" alt="Котик облизывается">
У изображений отсутствуют атрибуты с размерами

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +        </svg>
Это декоративное изображение, оно не должно быть в разметке.

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +        <svg width="67" height="50" viewBox="0 0 67 50" fill="none" xmlns="http://www.w3.org/2000/svg">
Это декоративное изображение, оно не должно быть в разметке.

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <div class="how-work__blok">
опечатка в слове block

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +        <svg class="how-work__img" xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="none">
все изображения в этой секции декоративные, их в разметке не должно быть

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <div class="how-work__blok">
опечатка в слове block

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <div class="live-model__rates rates">
Не вижу смысла здесь заводить блок "rates", если ниже не следуют его элементы.

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <div class="live-model__rates rates">
Не вижу смысла здесь заводить блок "rates", если ниже не следуют его элементы.

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +        <img class="live-model__after" href="./img/img-cat-slim-small.png" alt="Кот после программы">
Нету размеров

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +    <section class="road-map">
Название класса ну вообще не очень. 
Лучше что-то типа - "contacts", "about-us"

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +      <img class="road-map__img" src="./img/map-small.jpg" alt="Карта проезда">
потерял закрывающий тэг `</section>`

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +    </section>
этот тэг должен быть внутри `</main>`

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
> +        </svg>
все изображения декоративные

2024-01-20 16:34 UTC, vadimrahmanov commented on source/form.html
> +      <ul class="header__nav main-menu">
здесь замечания как на главной

2024-01-20 16:34 UTC, vadimrahmanov commented on source/form.html
> +    </section>
замечания по этой секции и футеру как на главной.

2024-01-20 16:34 UTC, vadimrahmanov commented on source/catalog.html
> +      <ul class="header__nav main-menu">
замечания как на главной

2024-01-20 16:34 UTC, vadimrahmanov commented on source/catalog.html
> +          <div class="catalog__card card">
откуда в этом блоке catalog__card?

2024-01-20 16:34 UTC, vadimrahmanov commented on source/catalog.html
> +    </section>
замечания по этой секции и футеру как на главной

2024-01-20 16:34 UTC, vadimrahmanov commented on source/catalog.html
У изображений нету атрибутов с размерами

2024-01-20 16:34 UTC, vadimrahmanov commented on source/catalog.html
Не проходит валидацию

2024-01-20 16:34 UTC, vadimrahmanov commented on source/index.html
Не проходит валидацию

2024-01-25 17:27 UTC, licos87 commented on source/index.html
> +        <svg class="how-work__img" xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="none">
тогда можно убрать все лишние дивы и просто оставить?
<section class="how-work">
      <h2 class="how-work__title">Как это работает</h2>
      <div class="how-work__block">
        <p class="how-work__text leaf">Функциональное питание содержит только полезные питательные вещества.</p>
        <p class="how-work__text hot-water">Выпускается в виде порошка, который нужно лишь залить кипятком и готово.</p>
        <p class="how-work__text eat">Замените один-два приема обычной еды на наше функциональное питание.</p>
        <p class="how-work__text scale">Уже через месяц наслаждайтесь изменениями к лучшему вашего питомца!</p>
      </div>
    </section>

2024-01-25 17:33 UTC, licos87 commented on source/index.html
> +        </svg>
тогда можно убрать все лишние дивы и просто оставить?
```
<section class="how-work">
      <h2 class="how-work__title">Как это работает</h2>
      <div class="how-work__block">
        <p class="how-work__text leaf">Функциональное питание содержит только полезные питательные вещества.</p>
        <p class="how-work__text hot-water">Выпускается в виде порошка, который нужно лишь залить кипятком и готово.</p>
        <p class="how-work__text eat">Замените один-два приема обычной еды на наше функциональное питание.</p>
        <p class="how-work__text scale">Уже через месяц наслаждайтесь изменениями к лучшему вашего питомца!</p>
      </div>
    </section>
```

2024-01-26 20:38 UTC, merged