Стилизация
htmlacademy-adaptive/323345-cat-energy-1 pull request #3
Opened 2024-02-08 19:02 UTC by licos87

---
:mortar_board: [Стилизация](https://up.htmlacademy.ru/adaptive-individual/1/user/323345/tasks/6)

2024-02-11 17:38 UTC, vadimrahmanov requested changes

2024-02-11 17:38 UTC, vadimrahmanov commented on source/catalog.html
Не проходит валидацию W3C. Помнишь у тебя была проблема с отображением svg в проекте Девайс? Вот тут может быть похожее, так как одинаковые id у элементов SVG.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/form.html
Тоже самое, что и на странице каталога в плане валидации.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/form.html
> +        <ul class="feedback__list">
Это элемент, а не блок. А куда сам блок подевался?

2024-02-11 17:38 UTC, vadimrahmanov commented on source/index.html
Не проходит валидацию W3C. Исправь все замечание из валидатора.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/card.scss
> +  margin: 10.5px 36px;
Не очень хорошая практика использовать дробные значения с пикселями. Допускается с % единицами.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/card.scss
> +  color: #222222;
Все цвета нужно вынести в переменные.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/card.scss
> +  color: #222222;
В переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/catalog.scss
> +  border-top: 1px solid #ebebeb;
цвета в переменную. Например color-border , если все границы имеют одинаковый цвет.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/catalog.scss
> +  border-bottom: 1px solid #ebebeb;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/catalog.scss
> +    background-color: #f2f2f2;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/catalog.scss
> +    color: #444444;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/catalog.scss
> +    background-color: #5eaa2f;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/catalog.scss
> +    background-color: #5eaa2f;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/catalog.scss
> +    color: rgb(255, 255, 255, 0.3);
здесь можно использовать sscss функцию rgba, а цвет предварительно в переменную.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/contacts.scss
> +  color: #111111;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/contacts.scss
> +  width: 280px;
Фиксированная ширина не очень будет удобна в плане адаптива

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/contacts.scss
> +  background-color: #f2f2f2;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/container.scss
> +  width: 280px;
Старайся вообще не использовать фиксированную ширину для контейнеров и каких-либо элементов, кроме картинок (если очень нужно)

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/diet.scss
> +  width: 280px;
Зачем ширина здесь фиксированная? У тебя mobile first. Просто делаешь паддинги по бокам и всё, а ширину вообще можно не указывать.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/diet.scss
> +  &--small::before {
Это можно вложить вовнутрь &--small

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/diet.scss
> +}
Эти вещи можно вкладывать вовнутрь модификаторов.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/diet.scss
> +    background-color: #d9d9d9;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/diet.scss
> +  color: #000000;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/diet.scss
> +  font-family: "Oswald", sans-serif;
Непонятные , где-то у тебя font-family в переменных, а где-то как здесь. Нужно однообразие.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/extra-product.scss
> +  color: #000000;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/extra-product.scss
> +    width: 280px;
Комментарий по поводу фиксированной ширины наверху.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/extra-product.scss
> +  color: #222222;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/extra-product.scss
> +}
Цвета в переменные

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/extra-product.scss
> +  border-top: 1px solid #cdcdcd;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/extra.scss
> +  border: 1px solid #cdcdcd;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  }
Цвета в переменные

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  color: #000000;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  color: #000000;
Цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  // margin: 13px 13px 14px 0;
закомментированный участок кода

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  border: 1px solid #e7e7e7;
цвета в переменные

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  border: 1px solid #cdcdcd;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  color: #000000;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  font-family: var(--font-family);
где-то у тебя SCSS переменные, а где-то вообще без них. А тут третий вариант :D с помощью нативных CSS перменных

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  background-color: #68b738;
цвета в переменные

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +    background-color: #5eaa2f;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  line-height: 125%;
Ты если везде в пикселях используешь, то и здесь пожалуйста тоже в пикселях. Это касается всех свойств, а не только line-height. Должно быть однообразие.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +    background-color: #5eaa2f;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/feedback.scss
> +  color: #000000;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +  background-color: #f2f2f2;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +.footer__nav--small::before {
так, модификатор может идти вовнутрь элемента, а before в него.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +  background-color: #d9d9d9;
тут тоже самое, что и сверху

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +}
делаешь класс .footer__item, а в него уже вкладываешь `&:focus-visible`

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +    background-color: #68b738;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +    background-color: #68b738;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +    background-color: #666666;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +    background-color: #666666;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +    background-color: #666666;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/footer.scss
> +  color: rgb(68, 68, 68);
почему цвет в rgb, а никак везде в HEX?

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/form.scss
> +  background-color: #ffffff;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/form.scss
> +  font-weight: 400;
Там где значение по-умолчанию и так такие, их не нужно указывать в CSS.  Это не только касается конкретно этого случая. У тебя много где так. Например font-style: normal; Это тоже ненужно указывать, т.к по-умолчанию и так такое свойство.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/form.scss
> +    max-width: 280px;
Про фиксированную ширину выше указал

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/gift.scss
> +  background: #68b738d9;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/gift.scss
> +  color: #ffffff;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/header.scss
> +  border-bottom: 1px solid #d9d9d9;
цвета в переменные

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/header.scss
> +  width: 68%;
Почему здесь ширина в %? Это же логотип, можно как раз в этом случае задать фиксированную для него.

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/how-work.scss
> +  color: #000000;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/how-work.scss
> +  font-weight: 400;
такое значение и так по-умолчанию

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +  background-color: #eaeaea;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +  color: #000000;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +  color: #000000;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +  color: #000000;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +  background-color: #666666;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +}
Это можно вложить вовнутрь .live-model__slider

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +  border: 4px solid #666666;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +  background: url("../../img/svg/dabl-arrow.svg") center center no-repeat #ffffff;
цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/live-model.scss
> +}
Тоже самое что и сверху, можно вложить

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/main-menu.scss
> +    transition: $trans-default;
цвета в переменные

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/main-menu.scss
> +  border-bottom: 1px solid#E6E6E6;
тут пробел надо и цвет в переменную

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/main-menu.scss
> +}
цвета в переменные везде

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/promo.scss
> +}
цвета в переменные

2024-02-11 17:38 UTC, vadimrahmanov commented on source/sass/blocks/promo.scss
> +  // height: 302px;
комментированные участки

2024-02-12 18:43 UTC, licos87 commented on source/form.html
> +        <ul class="feedback__list">
86 строка <fieldset class="feedback feedback--border">
сначала блок потом его модификатор

2024-02-19 08:54 UTC, merged